example.property= I AM DEV

# DataSource settings: set here your own configurations for the database
spring.datasource.url = jdbc:postgresql://localhost:5432/ostock_dev
spring.datasource.username = postgres
spring.datasource.password = {cipher}c0c95a77f0eb7a9833074e7fcbe72f783c1a496beb94cf8f8bb94b09739a0357